Repository cariodaporr/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#8 Integrar arquitetura v1.1
  arquitetura.md
Labels: Arquitera

#10 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#12 Integrar testes v1.0
  src/teste_inic.py
Labels: Teste

#13 Gerar release v1.0
  Docs/Requisitos.md
  arquitetura.md
  src/jogovelha.py
  src/teste_inic.py
Labels: Operações

#16 Integrar requisitos 1.2
  docs1.2/requisitos1.2.md
Labels: Analise

#18 Integrar arquitetura v1.2
  docs/arquitetura1-2.md
Labels: Arquitera

#20 Integrar implementação v1.2
  src/jogovelha1-2.py
Labels: Programação

#23 Gerar release v1.2
  docs/arquitetura1-2.md
  docs1.2/requisitos1.2.md
  src/jogovelha1-2.py
  src/testes_inic1-2.py
  src/testes_jogar1-2.py
Labels: Operações
